### ISSUE TITLE
建议可以优化一下项目分类排版

### ISSUE THREAD

**Issue by H-Sofie** [Royfor12/CQUT-electronic-information-engineering#6]
参考了别的学校的共享计划，我觉得我们的首页不够直观，为了让更多新接触到GitHub的人能利用上这个项目，建议重新按照每门课程来分类，若按照专业分类，各个专业之间学习的课程会有重叠。最好可以将英文改为中文便于使用者查找。

**Comment by Royfor12** [comment]
感谢您的建议，由于这个项目的前身是我的个人资料库，所以最早是按照学年分类的，我也是当一个学年结束后把资料打包上传的。最新上传的资料已经在尝试以科目分类了，我打算在我有空的时候（明年4月份之后）对之前的文件进行整理，然后为他做个网页以便于大家检索。

**Comment by H-Sofie** [comment]
感谢学长的努力和贡献了
